name: flexible_carousel_slider
description: A Very Good Project created by Very Good CLI.
version: 0.1.0


environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ">=6.0.0 <8.0.0"
